### ISSUE TITLE
action='count' doesn't work with config

### ISSUE THREAD

**Issue by dmartin-isp** [bw2/ConfigArgParse#175] opened 2020-03-25 17:48 UTC
p.add('--verbose', '-v', action='count', default=0 )

set verbose to 4 in the config file and you get:

error: Unexpected value for verbose: '4'. Expecting 'true', 'false', 'yes', 'no', '1' or '0'

https://github.com/bw2/ConfigArgParse/blob/master/configargparse.py#L739

**Comment by bw2** [comment] 2020-04-09 10:43
If you want to add better handing for argparse._CountAction, a PR would be appreciated.

**Comment by macfreek** [comment] 2021-02-22 15:56
I think this is a duplicate of #138

**Closed** 2021-03-01 00:57 UTC
