### ISSUE TITLE
inconsistent handling of string args using YAML config

### ISSUE THREAD

**Issue by jxstanford** [bw2/ConfigArgParse#94] opened 2017-08-08 14:28 UTC
Unquoted strings that start with a number appear to be treated differently than when quoted, or than other strings that don't start with a numbers.  Example:

Config:
```
begin_time: 6:30
end_time: 12:59
```
Code:
```
p.add('--begin_time', type=str, default='6:30', help='filter out aggregations before start time')
p.add('--end_time', type=str, default='12:59', help='filter out aggregations after end time')
ns, args = p.parse_known_args()
logger.debug("begin_time: %s, end_time: %s" % (ns.begin_time, ns.end_time))
```
Result:
`08-08 07:08 root         DEBUG    begin_time: 390, end_time: 779`

If the values in the config file are quoted, then it returns the expected result:

Config:
```
begin_time: '6:30'
end_time: '12:59'
```

Result:
`08-08 07:09 root         DEBUG    begin_time: 6:30, end_time: 12:59`

**Comment by IanFang** [comment] 2017-08-18 17:18
This is not a bug. It is because the wrong way to use yaml. As the yaml cookbook suggested, when you have special character ':' in your string, you should use single quotation mark.

**Comment by bw2** [comment] 2017-12-26 18:57
Thanks @IanFang . Closing.

**Closed by bw2** 2017-12-26 18:57 UTC
