### ISSUE TITLE
"allow_abbrev=False" doesn't work

### ISSUE THREAD

**Issue by londumas** [bw2/ConfigArgParse#77] opened 2016-11-15 13:27 UTC
With the following code:

```
import configargparse

parser = configargparse.ArgParser(allow_abbrev=False)

parser.add('--aaa',type=types.IntType,required=False)

args = parser.parse_args()

print args
```

doing the following command line works, it shouldn't
```
python test_configargparse_abbreviation.py --a 1
```
Namespace(aaa=1)

**Comment by bw2** [comment] 2017-04-30 14:06
A PR to fix this would be appreciated.

**Comment by bpiotr** [comment] 2017-08-30 14:41
@londumas : what Python version are you using? Python 3 does not have types.IntType and there is no allow_abbrev in argparse of Python 2 - it always allows abbreviations. I'd suggest to close this.

**Comment by londumas** [comment] 2017-08-30 15:12
@bpiotr , I don't see the link with the Python version.
When setting "allow_abbrev=False", we shouldn't be able to set "aaa" through "a".
Anyway, I use Python2

**Comment by bpiotr** [comment] 2017-08-30 20:33
@londumas The issue is that allow_abbrev argument was introduced in argparse for Python 3.5. This argument does not exist in argparse for Python 2.

**Comment by bw2** [comment] 2017-12-26 18:58
Fixed by merged PR

**Closed by bw2** 2017-12-26 18:58 UTC
